FROM python:3.11-slim

WORKDIR /app

ENV PYTHONPATH=/app:$PYTHONPATH

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir streamlit requests pandas

COPY ./.streamlit /app/.streamlit
COPY ./ui /app/ui

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]
