"""
Database and vector store seeder for canonical enterprise documents.
Provides the standard dataset required for verification benchmarks (SRS Section 10.2).
"""

import logging
import os
from pathlib import Path
import sys
from typing import Dict, List

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.db.session import sync_session_factory
from app.worker.diff_engine import DiffEngine

logger = logging.getLogger(__name__)

BENCHMARK_DOCUMENTS: List[Dict[str, object]] = [
    {
        "external_id": "DOC-HR-TRAVEL-01",
        "title": "Corporate Travel Reimbursement Policy",
        "classification": "internal",
        "allowed_roles": ["*"],
        "content": (
            "# Corporate Travel Reimbursement Policy\n\n"
            "All employees traveling for business can claim reimbursement.\n"
            "The daily travel meal reimbursement limit is $50/day. "
            "All expense receipts must be retained and submitted via the Concur portal within 14 business days of return."
        ),
    },
    {
        "external_id": "DOC-CORP-ENG-04",
        "title": "Staging Environment Guidelines",
        "classification": "internal",
        "allowed_roles": ["engineering"],
        "content": (
            "# Staging Environment Guidelines\n\n"
            "All staging workloads are hosted on the Kubernetes staging cluster.\n"
            "Staging cluster credentials rotate every 30 days via HashiCorp Vault. "
            "To access staging clusters, engineers must use kubectl with short-lived tokens "
            "generated by the internal auth proxy over port 9443."
        ),
    },
    {
        "external_id": "DOC-EXEC-COMP-01",
        "title": "Executive Leadership Compensation Structure",
        "classification": "executive",
        "allowed_roles": ["c-suite"],
        "content": (
            "# Executive Leadership Compensation Structure\n\n"
            "The Q3 executive bonus structure is indexed at 45% of base salary contingent upon achieving enterprise ARR targets. "
            "Only C-suite officers are eligible for this bonus tier."
        ),
    },
    {
        "external_id": "DOC-HR-COMP-02",
        "title": "General Employee Compensation and Benefits Policy",
        "classification": "internal",
        "allowed_roles": ["*"],
        "content": (
            "# General Employee Compensation and Benefits Policy\n\n"
            "Standard performance bonuses are reviewed annually during the Q4 cycle. "
            "Merit increases range between 3% and 7% based on team calibration and individual impact."
        ),
    },
    {
        "external_id": "DOC-HR-OFFBOARD-01",
        "title": "HR Employee Offboarding Procedures",
        "classification": "confidential",
        "allowed_roles": ["hr"],
        "content": (
            "# HR Employee Offboarding Procedures\n\n"
            "When an employee departs the organization, HR initiates an automated asset retrieval checklist.\n"
            "Security access revokes at 17:00 UTC on the final working day. "
            "Severance agreements and COBRA notices must be dispatched within 48 hours."
        ),
    },
    {
        "external_id": "DOC-OPS-WIFI-01",
        "title": "Office Facility Operations and WiFi Access",
        "classification": "internal",
        "allowed_roles": ["*"],
        "content": (
            "# Office Facility Operations\n\n"
            "The enterprise WiFi password is rotated quarterly and broadcast via WPA3-Enterprise credentials tied to Okta SSO. "
            "Guest networks are isolated on VLAN 40."
        ),
    },
    {
        "external_id": "DOC-LEGAL-CONTRACT-01",
        "title": "Master Services Agreement Standard Terms",
        "classification": "confidential",
        "allowed_roles": ["legal"],
        "content": (
            "# Master Services Agreement Standard Terms\n\n"
            "Our standard liability clause specifies that total aggregate liability shall not exceed the total fees paid by customer "
            "under the applicable order form during the preceding 12-month period."
        ),
    },
    {
        "external_id": "DOC-ENG-API-01",
        "title": "Core API Standards and Protocol Specification",
        "classification": "internal",
        "allowed_roles": ["engineering"],
        "content": (
            "# Core API Standards and Protocol Specification\n\n"
            "All internal microservices must adhere to OpenAPI 3.1 specifications with mutual TLS (mTLS) enabled. "
            "Protobuf gRPC is mandated for high-throughput inter-service communication."
        ),
    },
    {
        "external_id": "DOC-ENG-ROADMAP-01",
        "title": "2026 Engineering Architecture Roadmap",
        "classification": "internal",
        "allowed_roles": ["engineering"],
        "content": (
            "# 2026 Engineering Architecture Roadmap\n\n"
            "The 2026 engineering roadmap prioritizes zero-trust microservice federation and sub-second vector invalidation. "
            "Legacy batch vector indexing will be retired in Q2 2026."
        ),
    },
    {
        "external_id": "DOC-PUB-MISSION-01",
        "title": "Corporate Mission and Values Statement",
        "classification": "public",
        "allowed_roles": ["*"],
        "content": (
            "# Corporate Mission and Values Statement\n\n"
            "Our mission is to empower global connectivity through secure, scalable software. "
            "Our core values are Integrity, Innovation, and Inclusivity. We strive to serve our customers "
            "with transparency and excellence in every interaction."
        ),
    },
    {
        "external_id": "DOC-IT-SUPPORT-01",
        "title": "IT Helpdesk and Support SLAs",
        "classification": "internal",
        "allowed_roles": ["*"],
        "content": (
            "# IT Helpdesk and Support SLAs\n\n"
            "For all IT-related issues, please submit a ticket via Jira Service Desk. "
            "Severity 1 (Critical) issues have a 1-hour response SLA. "
            "Severity 2 (High) issues have a 4-hour response SLA. "
            "For immediate assistance, call the IT hotline at extension 4000."
        ),
    },
    {
        "external_id": "DOC-MKT-BRAND-01",
        "title": "Brand Guidelines and Logo Usage",
        "classification": "public",
        "allowed_roles": ["*"],
        "content": (
            "# Brand Guidelines and Logo Usage\n\n"
            "The corporate logo must always be displayed with a minimum of 20px clear space on all sides. "
            "Do not stretch, alter colors, or apply drop shadows to the logo. "
            "The primary brand color is Hex #1E88E5."
        ),
    },
    {
        "external_id": "DOC-HR-HOLIDAY-2026",
        "title": "2026 Corporate Holiday Schedule",
        "classification": "public",
        "allowed_roles": ["*"],
        "content": (
            "# 2026 Corporate Holiday Schedule\n\n"
            "The company will observe the following holidays in 2026: "
            "New Year's Day (Jan 1), Martin Luther King Jr. Day (Jan 19), Memorial Day (May 25), "
            "Independence Day (Jul 3), Labor Day (Sep 7), Thanksgiving (Nov 26-27), and Winter Break (Dec 24-31)."
        ),
    },
    {
        "external_id": "DOC-ENG-SECRETS-01",
        "title": "Production Secret Management",
        "classification": "confidential",
        "allowed_roles": ["engineering"],
        "content": (
            "# Production Secret Management\n\n"
            "Production database passwords and API keys must be managed exclusively via AWS Secrets Manager. "
            "Developers must never hardcode secrets in source code or environment files. "
            "Any exposed secrets must be rotated immediately and reported to the Security team."
        ),
    },
    {
        "external_id": "DOC-EXEC-ACQ-01",
        "title": "Project Phoenix Acquisition Target",
        "classification": "executive",
        "allowed_roles": ["c-suite"],
        "content": (
            "# Project Phoenix Acquisition Target\n\n"
            "Project Phoenix refers to the potential Q4 2026 acquisition of CloudNative Solutions Inc. "
            "The target valuation is capped at $45M. All discussions regarding this project are strictly under NDA."
        ),
    },
    {
        "external_id": "DOC-FIN-MERGERS-01",
        "title": "M&A Diligence Notes (Project Apollo)",
        "classification": "executive",
        "allowed_roles": ["finance", "c-suite"],
        "content": (
            "# M&A Diligence Notes (Project Apollo)\n\n"
            "Project Apollo targets the acquisition of a leading European payments gateway. "
            "Financial modeling suggests a $120M all-cash offer. "
            "Only the CFO and CEO are authorized to review the final term sheet."
        ),
    },
    {
        "external_id": "DOC-ENG-PROD-CREDS-01",
        "title": "Production Database Admin Credentials",
        "classification": "confidential",
        "allowed_roles": ["engineering"],
        "content": (
            "# Production Database Admin Credentials\n\n"
            "The root password for the European production database cluster is stored in AWS Secrets Manager under 'eu-prod-db-root'. "
            "Only senior engineering leads have the KMS key required to decrypt this value."
        ),
    },
    {
        "external_id": "DOC-HR-SALARY-GRID-01",
        "title": "2026 Salary Grid and Bonus Targets",
        "classification": "confidential",
        "allowed_roles": ["hr"],
        "content": (
            "# 2026 Salary Grid and Bonus Targets\n\n"
            "The updated salary bands for L6 Engineers cap at $250,000 base. "
            "All compensation exceptions must be approved by the VP of HR and the CEO."
        ),
    },
    {
        "external_id": "DOC-CON-HANDBOOK-01",
        "title": "Contractor Access and Onboarding Handbook",
        "classification": "internal",
        "allowed_roles": ["contractor", "hr"],
        "content": (
            "# Contractor Access and Onboarding Handbook\n\n"
            "Contractors are granted 90-day access tokens for the guest VPN. "
            "Contractors may not access the source code repositories without an explicit waiver from the VP of Engineering."
        ),
    },
    {
        "external_id": "DOC-SEC-AUDIT-01",
        "title": "Q3 Penetration Test Results and Zero-Days",
        "classification": "executive",
        "allowed_roles": ["engineering", "security"],
        "content": (
            "# Q3 Penetration Test Results\n\n"
            "The external audit revealed a critical zero-day vulnerability in the legacy payment gateway API. "
            "Exploitation requires physical access to the server VLAN. Immediate patching is scheduled for Q4."
        ),
    },
    {
        "external_id": "DOC-FIN-PAYROLL-01",
        "title": "Contractor Payroll and Invoice Procedures",
        "classification": "confidential",
        "allowed_roles": ["finance", "contractor"],
        "content": (
            "# Contractor Payroll and Invoice Procedures\n\n"
            "Contractors must submit their monthly net-30 invoices to the dedicated Finance portal. "
            "Invoices exceeding $15,000 require manual sign-off from the Finance Director before disbursement."
        ),
    },
    {
        "external_id": "DOC-CORP-REORG-01",
        "title": "2027 Corporate Restructuring Plan",
        "classification": "executive",
        "allowed_roles": ["c-suite", "hr"],
        "content": (
            "# 2027 Corporate Restructuring Plan\n\n"
            "To streamline operations, the European and Asian marketing divisions will be merged into a single Global Outreach department. "
            "This restructuring will eliminate 40 redundant positions. Communications will begin in January 2027."
        ),
    }
]


def seed_benchmark_corpus():
    """Seeds canonical enterprise documents into PostgreSQL and Qdrant."""
    print("=" * 70)
    print("Seeding SentinelRAG Benchmark Document Corpus...")
    print("=" * 70)

    session = sync_session_factory()
    try:
        diff_engine = DiffEngine()
        for doc in BENCHMARK_DOCUMENTS:
            print(f"[*] Ingesting: {doc['external_id']} ('{doc['title']}') [{doc['classification'].upper()}]")
            res = diff_engine.process_change(
                event_type="CREATE",
                document_id=str(doc["external_id"]),
                title=str(doc["title"]),
                classification=str(doc["classification"]),
                allowed_roles=list(doc["allowed_roles"]),
                content=str(doc["content"]),
                db_session=session,
            )
            print(f"    -> Generated {res['total_chunks']} chunks (embedding calls: {res['embedding_calls_generated']})")
        print("\n[SUCCESS] Benchmark corpus successfully seeded!")
    finally:
        session.close()


if __name__ == "__main__":
    seed_benchmark_corpus()
